spring:
  application:
    name: paymentDemo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/paymentDemo
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

razorpay:
  key-id: rzp_test_S5GacZlvaGFIuq
  key-secret: Th9kTiIjxHco5UgnPkGT6pR5

server:
  servlet:
    context-path: "/api"
  port: 8080
